version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 5
    versioning-strategy: "increase-if-necessary"
    groups:
      npm-production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 3
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
